<?php

declare(strict_types=1);

namespace Pentacore\Typefinder\Renderers;

use Illuminate\Database\Eloquent\Model;

class TypeScriptRenderer
{
    protected const FILE_HEADER = <<<'TS'
        // ───────────────────────────────────────────────────────────────────────
        // This file is auto-generated by laravel-typefinder.
        // Do not edit it by hand — re-run `php artisan typefinder:generate`.
        // https://github.com/pentacore/laravel-typefinder
        // ───────────────────────────────────────────────────────────────────────

        TS;

    /**
     * Render an enum to a .d.ts file content string.
     */
    public function renderEnum(array $enum): string
    {
        $name = $enum['name'];
        $values = $enum['values'];
        $backingType = $enum['backingType'];

        $valueStrings = array_map(function (string $value) use ($backingType): string {
            if ($backingType === 'string') {
                return sprintf("'%s'", $value);
            }

            return $value;
        }, $values);

        $union = implode(' | ', $valueStrings);

        return self::FILE_HEADER."\nexport type {$name} = {$union};\n";
    }

    /**
     * Render a model to a .d.ts file content string.
     *
     * @param  list<array>  $allEnums
     * @param  list<array>  $allModels
     */
    public function renderModel(array $model, array $allEnums, array $allModels): string
    {
        return $this->assembleFile([$this->buildModelBlock($model, $allEnums, $allModels)]);
    }

    /**
     * Render the Create companion type (omits server-filled fields and relationships).
     *
     * @param  list<array>  $allEnums
     * @param  list<array>  $allModels
     */
    public function renderModelCreate(array $model, array $allEnums, array $allModels): string
    {
        return $this->assembleFile([$this->buildModelCreateBlock($model, $allEnums, $allModels)]);
    }

    /**
     * Render the Update companion type: every assignable field becomes optional,
     * immutable-on-update fields are dropped. Relationships are excluded.
     *
     * @param  list<array>  $allEnums
     * @param  list<array>  $allModels
     * @param  list<string>  $immutable
     */
    public function renderModelUpdate(array $model, array $allEnums, array $allModels, array $immutable): string
    {
        return $this->assembleFile([$this->buildModelUpdateBlock($model, $allEnums, $allModels, $immutable)]);
    }

    /**
     * Render a single-file .d.ts containing the read shape plus — if enabled —
     * Create and Update companion types. Imports are unioned across all blocks.
     *
     * @param  list<array>  $allEnums
     * @param  list<array>  $allModels
     * @param  list<string>  $immutable
     */
    public function renderModelFile(array $model, array $allEnums, array $allModels, bool $emitWriteShapes, array $immutable): string
    {
        $blocks = [$this->buildModelBlock($model, $allEnums, $allModels)];

        if ($emitWriteShapes) {
            $blocks[] = $this->buildModelCreateBlock($model, $allEnums, $allModels);
            $blocks[] = $this->buildModelUpdateBlock($model, $allEnums, $allModels, $immutable);
        }

        return $this->assembleFile($blocks);
    }

    /**
     * @param  list<array>  $allEnums
     * @param  list<array>  $allModels
     * @return array{imports: list<string>, body: string}
     */
    protected function buildModelBlock(array $model, array $allEnums, array $allModels): array
    {
        $imports = [];
        $lines = [];

        $morphToRel = collect($model['relationships'] ?? [])->firstWhere('type', 'morphTo');

        $genericParam = '';
        if ($morphToRel && ! empty($morphToRel['morphTargets'])) {
            $targetNames = $this->resolveModelNames($morphToRel['morphTargets'], $allModels);
            $union = implode(' | ', $targetNames);
            $genericParam = sprintf('<T extends %s = %s>', $union, $union);

            foreach ($morphToRel['morphTargets'] as $target) {
                $targetName = $this->resolveModelName($target, $allModels);
                $imports[] = sprintf("import type { %s } from './%s';", $targetName, $targetName);
            }
        }

        foreach ($model['columns'] as $column) {
            $typeStr = $this->resolveTypeString($column['type'], $column['nullable'], $allEnums, $imports);
            $nullUnion = $column['nullable'] ? ' | null' : '';
            $lines[] = sprintf('  %s: %s%s;', $column['name'], $typeStr, $nullUnion);
        }

        foreach ($model['relationships'] ?? [] as $rel) {
            $relLine = $this->renderRelationshipField($rel, $allModels, $imports);
            if ($relLine !== null) {
                $lines[] = $relLine;
            }
        }

        $body = "export type {$model['name']}{$genericParam} = {\n".implode("\n", $lines)."\n};\n";

        return ['imports' => $imports, 'body' => $body];
    }

    /**
     * @param  list<array>  $allEnums
     * @param  list<array>  $allModels
     * @return array{imports: list<string>, body: string}
     */
    protected function buildModelCreateBlock(array $model, array $allEnums, array $allModels): array
    {
        $imports = [];
        $lines = [];

        $eligible = array_values(array_filter(
            $model['assignable_columns'] ?? [],
            fn (array $c): bool => empty($c['is_server_filled']),
        ));

        foreach ($eligible as $column) {
            $typeStr = $this->resolveTypeString($column['type'], $column['nullable'], $allEnums, $imports);
            $optional = $column['nullable'] ? '?' : '';
            $nullUnion = $column['nullable'] ? ' | null' : '';
            $lines[] = sprintf('  %s%s: %s%s;', $column['name'], $optional, $typeStr, $nullUnion);
        }

        $body = "export type {$model['name']}Create = {\n".implode("\n", $lines)."\n};\n";

        return ['imports' => $imports, 'body' => $body];
    }

    /**
     * @param  list<array>  $allEnums
     * @param  list<array>  $allModels
     * @param  list<string>  $immutable
     * @return array{imports: list<string>, body: string}
     */
    protected function buildModelUpdateBlock(array $model, array $allEnums, array $allModels, array $immutable): array
    {
        $imports = [];
        $lines = [];

        $eligible = array_values(array_filter(
            $model['assignable_columns'] ?? [],
            fn (array $c): bool => empty($c['is_server_filled']) && ! in_array($c['name'], $immutable, true),
        ));

        foreach ($eligible as $column) {
            $typeStr = $this->resolveTypeString($column['type'], $column['nullable'], $allEnums, $imports);
            $nullUnion = $column['nullable'] ? ' | null' : '';
            $lines[] = sprintf('  %s?: %s%s;', $column['name'], $typeStr, $nullUnion);
        }

        $body = "export type {$model['name']}Update = {\n".implode("\n", $lines)."\n};\n";

        return ['imports' => $imports, 'body' => $body];
    }

    /**
     * @param  list<array{imports: list<string>, body: string}>  $blocks
     */
    protected function assembleFile(array $blocks): string
    {
        $imports = [];
        $bodies = [];
        foreach ($blocks as $block) {
            foreach ($block['imports'] as $imp) {
                $imports[] = $imp;
            }

            $bodies[] = $block['body'];
        }

        $imports = array_values(array_unique($imports));
        sort($imports);

        $output = self::FILE_HEADER."\n";
        if ($imports !== []) {
            $output .= implode("\n", $imports)."\n\n";
        }

        return $output.implode("\n", $bodies);
    }

    /**
     * Render the consolidated pages.d.ts content.
     *
     * @param  list<array{component: string, props: array<string, string>, optional: list<string>}>  $pages
     * @param  list<array>  $allModels
     * @param  list<array>  $allEnums
     */
    public function renderPages(array $pages, array $allModels, array $allEnums): string
    {
        $imports = [];
        $entries = [];

        foreach ($pages as $page) {
            $propLines = [];
            foreach ($page['props'] as $name => $type) {
                $resolved = $this->resolvePagePropType((string) $type, $allModels, $allEnums, $imports);
                $optional = in_array($name, $page['optional'], true) ? '?' : '';
                $propLines[] = sprintf('%s%s: %s', $name, $optional, $resolved);
            }

            $entries[] = sprintf("  '%s': { ", $page['component']).implode('; ', $propLines).' };';
        }

        $imports = array_values(array_unique($imports));
        sort($imports);

        $output = self::FILE_HEADER."\n";
        if ($imports !== []) {
            $output .= implode("\n", $imports)."\n\n";
        }

        $output .= "export type PageProps = {\n";
        $output .= implode("\n", $entries)."\n";
        $output .= "};\n\n";

        return $output."export type PageName = keyof PageProps;\n";
    }

    /**
     * @param  list<array>  $allModels
     * @param  list<array>  $allEnums
     * @param  list<string>  $imports
     */
    protected function resolvePagePropType(string $type, array $allModels, array $allEnums, array &$imports): string
    {
        if (class_exists($type) && is_subclass_of($type, Model::class)) {
            $short = $this->resolveModelName($type, $allModels);
            $imports[] = sprintf("import type { %s } from './models';", $short);

            return $short;
        }

        if (enum_exists($type)) {
            $short = $this->resolveEnumName($type, $allEnums);
            $imports[] = sprintf("import type { %s } from './enums';", $short);

            return $short;
        }

        return $type;
    }

    /**
     * Render a request to a .d.ts file content string.
     *
     * @param  list<array>  $allEnums
     */
    public function renderRequest(array $request, array $allEnums, bool $extractNested = false): string
    {
        $imports = [];
        $extractedTypes = [];
        $lines = [];

        foreach ($request['fields'] as $field) {
            $this->renderRequestField($field, $request['name'], $allEnums, $imports, $lines, $extractedTypes, $extractNested);
        }

        $imports = array_values(array_unique($imports));
        sort($imports);

        $output = self::FILE_HEADER."\n";
        if ($imports !== []) {
            $output .= implode("\n", $imports)."\n\n";
        }

        foreach ($extractedTypes as $extractedType) {
            $output .= $extractedType."\n\n";
        }

        $output .= "export type {$request['name']} = {\n";
        $output .= implode("\n", $lines)."\n";

        return $output."};\n";
    }

    /**
     * Render a pivot type to a .d.ts file content string.
     */
    public function renderPivot(array $pivot): string
    {
        $lines = [];

        foreach ($pivot['columns'] as $column) {
            $nullable = $column['nullable'] ?? false;
            $nullUnion = $nullable ? ' | null' : '';
            $lines[] = sprintf('  %s: %s%s;', $column['name'], $column['type'], $nullUnion);
        }

        if ($pivot['withTimestamps'] ?? false) {
            $lines[] = '  created_at: string | null;';
            $lines[] = '  updated_at: string | null;';
        }

        return self::FILE_HEADER."\nexport type {$pivot['name']} = {\n".implode("\n", $lines)."\n};\n";
    }

    /**
     * Render a barrel index.d.ts file.
     *
     * @param  list<string>  $typeNames
     */
    public function renderBarrelIndex(array $typeNames): string
    {
        $lines = array_map(
            fn (string $name): string => sprintf("export type { %s } from './%s';", $name, $name),
            $typeNames
        );

        return self::FILE_HEADER."\n".implode("\n", $lines)."\n";
    }

    /**
     * Render the top-level barrel index.d.ts file.
     *
     * @param  list<string>  $categories
     */
    public function renderTopLevelBarrel(array $categories): string
    {
        $lines = array_map(
            fn (string $cat): string => sprintf("export type * from './%s';", $cat),
            $categories
        );

        return self::FILE_HEADER."\n".implode("\n", $lines)."\n";
    }

    /**
     * Resolve a type value to a TypeScript type string.
     *
     * @param  list<array>  $allEnums
     * @param  list<string>  $imports  (passed by reference)
     */
    protected function resolveTypeString(mixed $type, bool $nullable, array $allEnums, array &$imports): string
    {
        if (is_string($type)) {
            return $type;
        }

        if (is_array($type)) {
            if (isset($type['enum'])) {
                $enumName = $this->resolveEnumName($type['enum'], $allEnums);
                $imports[] = sprintf("import type { %s } from '../enums';", $enumName);

                return $enumName;
            }

            if (isset($type['enumCollection'])) {
                $enumName = $this->resolveEnumName($type['enumCollection'], $allEnums);
                $imports[] = sprintf("import type { %s } from '../enums';", $enumName);

                return $enumName.'[]';
            }

            if (isset($type['in'])) {
                $values = array_map(fn (string $v): string => sprintf("'%s'", $v), $type['in']);

                return implode(' | ', $values);
            }

            if (isset($type['anyOf'])) {
                return implode(' | ', array_unique($type['anyOf']));
            }
        }

        return 'unknown';
    }

    /**
     * Render a relationship as a type field line.
     */
    protected function renderRelationshipField(array $rel, array $allModels, array &$imports): ?string
    {
        $name = $rel['name'];

        switch ($rel['type']) {
            case 'one':
            case 'belongsTo':
                $relatedName = $this->resolveModelName($rel['related'], $allModels);
                $imports[] = sprintf("import type { %s } from './%s';", $relatedName, $relatedName);

                return sprintf('  %s?: %s | null;', $name, $relatedName);

            case 'many':
                $relatedName = $this->resolveModelName($rel['related'], $allModels);
                $imports[] = sprintf("import type { %s } from './%s';", $relatedName, $relatedName);

                return sprintf('  %s?: %s[];', $name, $relatedName);

            case 'manyWithPivot':
                $relatedName = $this->resolveModelName($rel['related'], $allModels);
                $imports[] = sprintf("import type { %s } from './%s';", $relatedName, $relatedName);
                $pivotName = $this->generatePivotName($rel['pivot']['table'] ?? $name);
                $imports[] = sprintf("import type { %s } from '../pivots';", $pivotName);

                return sprintf('  %s?: (%s & { pivot: %s })[];', $name, $relatedName, $pivotName);

            case 'morphTo':
                return sprintf('  %s?: T | null;', $name);

            default:
                return null;
        }
    }

    /**
     * Render a request field (top-level line only; nested recursion handled here).
     */
    protected function renderRequestField(
        array $field,
        string $requestName,
        array $allEnums,
        array &$imports,
        array &$lines,
        array &$extractedTypes,
        bool $extractNested,
        int $indent = 1,
    ): void {
        $prefix = str_repeat('  ', $indent);
        $optional = $field['required'] ? '' : '?';
        $nullUnion = $field['nullable'] ? ' | null' : '';

        if ($field['type'] === 'object' && isset($field['children'])) {
            if ($extractNested) {
                $nestedName = $requestName.ucfirst((string) $field['name']);
                $nestedLines = [];
                foreach ($field['children'] as $child) {
                    $childOptional = $child['required'] ? '' : '?';
                    $childNull = $child['nullable'] ? ' | null' : '';
                    $childType = $this->resolveTypeString($child['type'], $child['nullable'], $allEnums, $imports);
                    $nestedLines[] = sprintf('  %s%s: %s%s;', $child['name'], $childOptional, $childType, $childNull);
                }

                $extractedTypes[] = "export type {$nestedName} = {\n".implode("\n", $nestedLines)."\n};";
                $lines[] = sprintf('%s%s%s: %s%s;', $prefix, $field['name'], $optional, $nestedName, $nullUnion);
            } else {
                $lines[] = sprintf('%s%s%s: {', $prefix, $field['name'], $optional);
                foreach ($field['children'] as $child) {
                    $childOptional = $child['required'] ? '' : '?';
                    $childNull = $child['nullable'] ? ' | null' : '';
                    $childType = $this->resolveTypeString($child['type'], $child['nullable'], $allEnums, $imports);
                    $lines[] = sprintf('%s  %s%s: %s%s;', $prefix, $child['name'], $childOptional, $childType, $childNull);
                }

                $lines[] = sprintf('%s}%s;', $prefix, $nullUnion);
            }
        } else {
            $typeStr = $this->resolveTypeString($field['type'], $field['nullable'], $allEnums, $imports);
            $lines[] = sprintf('%s%s%s: %s%s;', $prefix, $field['name'], $optional, $typeStr, $nullUnion);
        }
    }

    protected function resolveEnumName(string $fqcn, array $allEnums): string
    {
        foreach ($allEnums as $allEnum) {
            if ($allEnum['fqcn'] === $fqcn) {
                return $allEnum['name'];
            }
        }

        $parts = explode('\\', $fqcn);

        return end($parts);
    }

    protected function resolveModelName(string $fqcn, array $allModels): string
    {
        foreach ($allModels as $allModel) {
            if ($allModel['fqcn'] === $fqcn) {
                return $allModel['name'];
            }
        }

        $parts = explode('\\', $fqcn);

        return end($parts);
    }

    /**
     * @return list<string>
     */
    protected function resolveModelNames(array $fqcns, array $allModels): array
    {
        return array_map(fn (string $fqcn): string => $this->resolveModelName($fqcn, $allModels), $fqcns);
    }

    protected function generatePivotName(string $tableName): string
    {
        return str_replace(' ', '', ucwords(str_replace('_', ' ', $tableName))).'Pivot';
    }
}
