<?php

declare(strict_types=1);

namespace Pentacore\Typefinder\Renderers;

use Illuminate\Database\Eloquent\Model;
use Pentacore\Typefinder\Renderers\Concerns\RendersBroadcasting;
use Pentacore\Typefinder\Renderers\Concerns\RendersModels;
use Pentacore\Typefinder\Renderers\Concerns\RendersResources;

class TypeScriptRenderer
{
    use RendersBroadcasting;
    use RendersModels;
    use RendersResources;

    public const string FILE_HEADER = <<<'TS'
        // ───────────────────────────────────────────────────────────────────────
        // This file is auto-generated by laravel-typefinder.
        // Do not edit it by hand — re-run `php artisan typefinder:generate`.
        // https://github.com/pentacore/laravel-typefinder
        // ───────────────────────────────────────────────────────────────────────

        TS;

    /**
     * Render an enum to a file content string.
     *
     * When $emitValues is false (default), produces a `.d.ts`-style union
     * type alias. When true, produces a `.ts` file pairing an `as const`
     * object with a matching type derived from it — giving consumers both
     * a runtime value for iteration (`Object.values(PostStatus)`) and the
     * same union type for parameters. Callers must write the output to a
     * `.ts` file in that case; barrels should also be `.ts` so the runtime
     * export isn't stripped.
     */
    public function renderEnum(array $enum, bool $emitValues = false): string
    {
        $name = $enum['name'];
        $backingType = $enum['backingType'];

        if (! $emitValues) {
            $valueStrings = array_map(function (string|int $value) use ($backingType): string {
                if ($backingType === 'string') {
                    return sprintf("'%s'", $value);
                }

                return (string) $value;
            }, $enum['values']);

            $union = implode(' | ', $valueStrings);

            return self::FILE_HEADER."\nexport type {$name} = {$union};\n";
        }

        $cases = $enum['cases'] ?? [];
        $entries = array_map(function (array $case) use ($backingType): string {
            $value = $backingType === 'string'
                ? sprintf("'%s'", $case['value'])
                : (string) $case['value'];

            return sprintf('    %s: %s,', $case['name'], $value);
        }, $cases);

        $body = "export const {$name} = {\n".implode("\n", $entries)."\n} as const;\n\n";
        $body .= "export type {$name} = typeof {$name}[keyof typeof {$name}];\n";

        return self::FILE_HEADER."\n".$body;
    }

    /**
     * Render the consolidated pages.d.ts content.
     *
     * @param  list<array{component: string, props: array<string, string>, optional: list<string>}>  $pages
     * @param  list<array>  $allModels
     * @param  list<array>  $allEnums
     */
    public function renderPages(array $pages, array $allModels, array $allEnums): string
    {
        $imports = [];
        $entries = [];

        foreach ($pages as $page) {
            $propLines = [];
            foreach ($page['props'] as $name => $type) {
                $resolved = $this->resolvePagePropType((string) $type, $allModels, $allEnums, $imports);
                $optional = in_array($name, $page['optional'], true) ? '?' : '';
                $propLines[] = sprintf('%s%s: %s', $name, $optional, $resolved);
            }

            $entries[] = sprintf("  '%s': { ", $page['component']).implode('; ', $propLines).' };';
        }

        $imports = array_values(array_unique($imports));
        sort($imports);

        $output = self::FILE_HEADER."\n";
        if ($imports !== []) {
            $output .= implode("\n", $imports)."\n\n";
        }

        $output .= "export type PageProps = {\n";
        $output .= implode("\n", $entries)."\n";
        $output .= "};\n\n";

        return $output."export type PageName = keyof PageProps;\n";
    }

    /**
     * @param  list<array>  $allModels
     * @param  list<array>  $allEnums
     * @param  list<string>  $imports
     */
    protected function resolvePagePropType(string $type, array $allModels, array $allEnums, array &$imports): string
    {
        if (class_exists($type) && is_subclass_of($type, Model::class)) {
            $short = $this->resolveModelName($type, $allModels);
            $imports[] = sprintf("import type { %s } from './models';", $short);

            return $short;
        }

        if (enum_exists($type)) {
            $short = $this->resolveEnumName($type, $allEnums);
            $imports[] = sprintf("import type { %s } from './enums';", $short);

            return $short;
        }

        return $type;
    }

    /**
     * Render a request to a .d.ts file content string.
     *
     * @param  list<array>  $allEnums
     */
    public function renderRequest(array $request, array $allEnums, bool $extractNested = false): string
    {
        $imports = [];
        $extractedTypes = [];
        $lines = [];

        foreach ($request['fields'] as $field) {
            $this->renderRequestField($field, $request['name'], $allEnums, $imports, $lines, $extractedTypes, $extractNested);
        }

        $imports = array_values(array_unique($imports));
        sort($imports);

        $output = self::FILE_HEADER."\n";
        if ($imports !== []) {
            $output .= implode("\n", $imports)."\n\n";
        }

        foreach ($extractedTypes as $extractedType) {
            $output .= $extractedType."\n\n";
        }

        if ($lines === []) {
            return $output."export type {$request['name']} = Record<string, never>;\n";
        }

        $output .= "export type {$request['name']} = {\n";
        $output .= implode("\n", $lines)."\n";

        return $output."};\n";
    }

    /**
     * Render a pivot type to a .d.ts file content string.
     */
    public function renderPivot(array $pivot): string
    {
        $lines = [];

        foreach ($pivot['columns'] as $column) {
            $nullable = $column['nullable'] ?? false;
            $nullUnion = $nullable ? ' | null' : '';
            $lines[] = sprintf('  %s: %s%s;', $column['name'], $column['type'], $nullUnion);
        }

        if ($pivot['withTimestamps'] ?? false) {
            $lines[] = '  created_at: string | null;';
            $lines[] = '  updated_at: string | null;';
        }

        return self::FILE_HEADER."\nexport type {$pivot['name']} = {\n".implode("\n", $lines)."\n};\n";
    }

    /**
     * Render a barrel index.d.ts file.
     *
     * @param  list<string>  $typeNames
     */
    /**
     * Render a JSON resource (.d.ts) file content.
     *
     * @param  array{name: string, fqcn: string, shape: array}  $resource
     * @param  list<array>  $allModels
     * @param  list<array>  $allEnums
     * @param  list<array>  $allResources
     */
    public function renderHelpers(): string
    {
        return self::FILE_HEADER."\n".<<<'TS'
export type Wrapped<T> = { data: T };

export type WrappedCollection<T> = { data: T[] };

export type PaginatedCollection<T> = WrappedCollection<T> & {
  links: {
    first: string | null;
    last: string | null;
    prev: string | null;
    next: string | null;
  };
  meta: {
    current_page: number;
    from: number | null;
    last_page: number;
    path: string;
    per_page: number;
    to: number | null;
    total: number;
    links: Array<{ url: string | null; label: string; active: boolean }>;
  };
};

export type CursorPaginatedCollection<T> = WrappedCollection<T> & {
  meta: {
    path: string;
    per_page: number;
    next_cursor: string | null;
    prev_cursor: string | null;
  };
};

export type SimplePaginatedCollection<T> = WrappedCollection<T> & {
  meta: {
    current_page: number;
    from: number | null;
    path: string;
    per_page: number;
    to: number | null;
  };
};

export type ValidationErrorResponse = {
  message: string;
  errors: Record<string, string[]>;
};

export type ErrorResponse = { message: string };

TS;
    }

    public function renderBarrelIndex(array $typeNames): string
    {
        $lines = array_map(
            fn (string $name): string => sprintf("export type { %s } from './%s';", $name, $name),
            $typeNames
        );

        return self::FILE_HEADER."\n".implode("\n", $lines)."\n";
    }

    /**
     * Render the top-level barrel index.d.ts file.
     *
     * @param  list<string>  $categories
     */
    public function renderTopLevelBarrel(array $categories): string
    {
        $lines = array_map(
            fn (string $cat): string => sprintf("export type * from './%s';", $cat),
            $categories
        );

        return self::FILE_HEADER."\n".implode("\n", $lines)."\n";
    }

    /**
     * Resolve a type value to a TypeScript type string.
     *
     * @param  list<array>  $allEnums
     * @param  list<string>  $imports  (passed by reference)
     */
    protected function resolveTypeString(mixed $type, bool $nullable, array $allEnums, array &$imports): string
    {
        if (is_string($type)) {
            return $type;
        }

        if (is_array($type)) {
            if (isset($type['enum'])) {
                $enumName = $this->resolveEnumName($type['enum'], $allEnums);
                $imports[] = sprintf("import type { %s } from '../enums';", $enumName);

                return $enumName;
            }

            if (isset($type['enumCollection'])) {
                $enumName = $this->resolveEnumName($type['enumCollection'], $allEnums);
                $imports[] = sprintf("import type { %s } from '../enums';", $enumName);

                return $enumName.'[]';
            }

            if (isset($type['in'])) {
                $values = array_map(fn (string $v): string => sprintf("'%s'", $v), $type['in']);

                return implode(' | ', $values);
            }

            if (isset($type['anyOf'])) {
                return implode(' | ', array_unique($type['anyOf']));
            }
        }

        return 'unknown';
    }

    /**
     * Render a relationship as a type field line.
     */
    protected function renderRelationshipField(array $rel, array $allModels, array &$imports): ?string
    {
        $name = $rel['name'];

        switch ($rel['type']) {
            case 'one':
            case 'belongsTo':
                $relatedName = $this->resolveModelName($rel['related'], $allModels);
                $imports[] = sprintf("import type { %s } from './%s';", $relatedName, $relatedName);

                return sprintf('  %s?: %s | null;', $name, $relatedName);

            case 'many':
                $relatedName = $this->resolveModelName($rel['related'], $allModels);
                $imports[] = sprintf("import type { %s } from './%s';", $relatedName, $relatedName);

                return sprintf('  %s?: %s[];', $name, $relatedName);

            case 'manyWithPivot':
                $relatedName = $this->resolveModelName($rel['related'], $allModels);
                $imports[] = sprintf("import type { %s } from './%s';", $relatedName, $relatedName);
                $pivotName = $this->generatePivotName($rel['pivot']['table'] ?? $name);
                $imports[] = sprintf("import type { %s } from './%s';", $pivotName, $pivotName);

                return sprintf('  %s?: (%s & { pivot: %s })[];', $name, $relatedName, $pivotName);

            case 'morphTo':
                return sprintf('  %s?: T | null;', $name);

            default:
                return null;
        }
    }

    /**
     * Render a request field (top-level line only; nested recursion handled here).
     */
    protected function renderRequestField(
        array $field,
        string $requestName,
        array $allEnums,
        array &$imports,
        array &$lines,
        array &$extractedTypes,
        bool $extractNested,
        int $indent = 1,
    ): void {
        $prefix = str_repeat('  ', $indent);
        $optional = $field['required'] ? '' : '?';
        $nullUnion = $field['nullable'] ? ' | null' : '';

        if ($field['type'] === 'object' && isset($field['children'])) {
            if ($extractNested) {
                $nestedName = $requestName.ucfirst((string) $field['name']);
                $nestedLines = [];
                foreach ($field['children'] as $child) {
                    $childOptional = $child['required'] ? '' : '?';
                    $childNull = $child['nullable'] ? ' | null' : '';
                    $childType = $this->resolveTypeString($child['type'], $child['nullable'], $allEnums, $imports);
                    $nestedLines[] = sprintf('  %s%s: %s%s;', $child['name'], $childOptional, $childType, $childNull);
                }

                $extractedTypes[] = "export type {$nestedName} = {\n".implode("\n", $nestedLines)."\n};";
                $lines[] = sprintf('%s%s%s: %s%s;', $prefix, $field['name'], $optional, $nestedName, $nullUnion);
            } else {
                $lines[] = sprintf('%s%s%s: {', $prefix, $field['name'], $optional);
                foreach ($field['children'] as $child) {
                    $childOptional = $child['required'] ? '' : '?';
                    $childNull = $child['nullable'] ? ' | null' : '';
                    $childType = $this->resolveTypeString($child['type'], $child['nullable'], $allEnums, $imports);
                    $lines[] = sprintf('%s  %s%s: %s%s;', $prefix, $child['name'], $childOptional, $childType, $childNull);
                }

                $lines[] = sprintf('%s}%s;', $prefix, $nullUnion);
            }
        } else {
            $typeStr = $this->resolveTypeString($field['type'], $field['nullable'], $allEnums, $imports);
            $lines[] = sprintf('%s%s%s: %s%s;', $prefix, $field['name'], $optional, $typeStr, $nullUnion);
        }
    }

    protected function resolveEnumName(string $fqcn, array $allEnums): string
    {
        foreach ($allEnums as $allEnum) {
            if ($allEnum['fqcn'] === $fqcn) {
                return $allEnum['name'];
            }
        }

        $parts = explode('\\', $fqcn);

        return end($parts);
    }

    protected function resolveModelName(string $fqcn, array $allModels): string
    {
        foreach ($allModels as $allModel) {
            if ($allModel['fqcn'] === $fqcn) {
                return $allModel['name'];
            }
        }

        $parts = explode('\\', $fqcn);

        return end($parts);
    }

    /**
     * @return list<string>
     */
    protected function resolveModelNames(array $fqcns, array $allModels): array
    {
        return array_map(fn (string $fqcn): string => $this->resolveModelName($fqcn, $allModels), $fqcns);
    }

    protected function generatePivotName(string $tableName): string
    {
        return str_replace(' ', '', ucwords(str_replace('_', ' ', $tableName))).'Pivot';
    }
}
